version: 2
registries:
  eclipse:
    type: maven-repository
    url: https://repo.eclipse.org/content/repositories/cbi-releases/
updates:
  - package-ecosystem: "maven"
    directory: "/"
    registries: "*"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
    allow:
      - dependency-name: "org.eclipse.cbi.maven.plugins:*"
      - dependency-name: "org.apache.maven.plugins:maven-clean-plugin"
  - package-ecosystem: "maven"
    directory: "/org.jacoco.core"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "component: core"
    allow:
      - dependency-name: "org.ow2.asm:*"
  - package-ecosystem: "maven"
    directory: "/org.jacoco.ant"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "component: ant"
    allow:
      - dependency-name: "org.apache.ant:*"
  - package-ecosystem: "maven"
    directory: "/org.jacoco.build"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "component: build"
    allow:
      - dependency-name: "org.apache.maven.plugins:*"
      - dependency-name: "org.codehaus.mojo:*"
      - dependency-name: "com.diffplug.spotless:*"
      - dependency-name: "org.sonarsource.scanner.maven:*"
    ignore:
      # TODO add comment
      - dependency-name: "org.apache.maven.plugins:maven-plugin-plugin"
      - dependency-name: "org.apache.maven.plugins:maven-invoker-plugin"
      # Requires Java 6
      - dependency-name: "org.apache.maven.plugins:maven-surefire-plugin"
        versions: ">=2.20.0"
    open-pull-requests-limit: 20
