version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
    allow:
      - dependency-name: "org.ow2.asm:*"
      - dependency-name: "org.apache.maven.plugins:*"
      - dependency-name: "org.codehaus.mojo:*"
      - dependency-name: "org.jetbrains.kotlin:*"
    ignore:
      # TODO add comment
      - dependency-name: "org.apache.maven.plugins:maven-plugin-plugin"
      - dependency-name: "org.apache.maven.plugins:maven-invoker-plugin"
      # Requires Java 6
      - dependency-name: "org.apache.maven.plugins:maven-surefire-plugin"
        versions: ">=2.20.0"
      # Requires Java 8
      - dependency-name: "org.apache.ant:ant"
        versions: ">=1.10.0"
