version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "component: core"
    allow:
      - dependency-name: "org.ow2.asm:*"
  - package-ecosystem: "maven"
    directory: "/org.jacoco.build"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "component: build"
    allow:
      - dependency-name: "org.apache.maven.plugins:*"
      - dependency-name: "org.codehaus.mojo:*"
    ignore:
      # TODO add comment
      - dependency-name: "org.apache.maven.plugins:maven-plugin-plugin"
      - dependency-name: "org.apache.maven.plugins:maven-invoker-plugin"
      # Requires Java 6
      - dependency-name: "org.apache.maven.plugins:maven-surefire-plugin"
        versions: ">=2.20.0"
    open-pull-requests-limit: 10
