on:
  pull_request_target:
    types: [assigned]
permissions:
  pull-requests: write
jobs:
  dependabot:
    runs-on: ubuntu-latest
    # Checking the author will prevent your Action run failing on non-Dependabot PRs
    if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@v1
      - name: label
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{ github.token }}
        run: |
          case "${{steps.dependabot-metadata.outputs.dependency-names}}" in
            org.ow2.asm:*)
              label="dependencies,test1";;
            *)
              label="dependencies,test2";;
          esac
          gh pr edit $PR_URL --add-label $label
